version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: docker/Dockerfile-php8
        restart: always
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
          - backend-storage:/app/storage/app
        networks:
            - academic-assistant
        command: /docker-start.sh

    mysql:
        build:
            context: .
            dockerfile: docker/Dockerfile-mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'backend-mysql:/var/lib/mysql'
        networks:
            - academic-assistant
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        restart: always
        volumes:
            - 'backend-redis:/data'
        networks:
            - academic-assistant
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        restart: always
        environment:
            PMA_HOST: mysql
        ports:
            - "8010:80"
volumes:
    backend-mysql:
    backend-redis:
    backend-storage:

networks:
    academic-assistant:
        driver: bridge
        external: true

